version: '3.3'

services:
  app:
    build: 
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - node-network
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node app.js
    container_name: app
  nginx:
    build: ./docker/nginx
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app
    container_name: nginx
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - node-network

networks:
  node-network:
    driver: bridge